
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationMenu from "@/components/navbar/navigation-menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="max-h-screen flex flex-col">
        {/* header */}
        <header>
          <NavigationMenu />
        </header>
          {children}
        <footer className="text-3xl mb-5 p-2 bg-gray-950 border-gray-700 border-t">this is footer</footer>
        {/* footer */}
      </body>
    </html>
  );
}
